language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: F+6jFHuAvA/V5ghMfihdFSRxCFkHdEb1LJU0vAuY7uVTsomGpvzm8KA85aA6tahCa2zIEqL/4tZuweXz98USbT/pK6GQmmtALu4tq+dAJfn9Mh9ziJe09L3X6fWUa+W5tZrBiJBEP9MFUL+MXbAKCdUv9WKfXTUR1aHU8IOOHCQ=
deploy:
  provider: nodejitsu
  skip_cleanup: true
  user: boennemann
  api_key:
    secure: WZJu/cg7eZuB2m8k/q0sZ4XGWpC2tuZCwgSIas9Dl+ku9H3BoCNSRbDAEWoQ4M6gvtqlXcUCRsFiIBTIJ2iWYGpaHRkkgRWHtmLBUrsU145hpBaXbUYGhpSiZ+4895xo1IsCHxJgb7Lf3VJA+X5BIdR4uJMUUgaG8tDpuTnb6D8=
  on:
    repo: boennemann/zentodone
    tags: true
    all_branches: true
