language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower grunt-cli
- bower install
cache:
  directories:
  - node_modules
env:
  global:
  - SAUCE_USERNAME=zentodone
  - secure: eSj7fV8Kn/irs8eN3cXaNXsNBzxAXzdzr9gh1K317LF1a/GlEL3OjjRQoWVUeqEBfyPfxKrzfrS3dKpU51Gotg4zKrcXpFKwIYnhfKsKNVWOoVz5jl8HoMMy/BM5MGTyfAm24Xx9FRlj6d0agw59TE44UehwUeYjFbHiSb3ojHE=
notifications:
  email: false
  slack:
    secure: F+6jFHuAvA/V5ghMfihdFSRxCFkHdEb1LJU0vAuY7uVTsomGpvzm8KA85aA6tahCa2zIEqL/4tZuweXz98USbT/pK6GQmmtALu4tq+dAJfn9Mh9ziJe09L3X6fWUa+W5tZrBiJBEP9MFUL+MXbAKCdUv9WKfXTUR1aHU8IOOHCQ=
deploy:
  provider: nodejitsu
  skip_cleanup: true
  user: boennemann
  api_key:
    secure: AmDQfQ89Wwzj/6VIvd2UVLmtZLRChRNcuowPXo+SDgeWGJQGkshLrp2bqz+ooLIZ769dqmPNe6zFZtzN2ujZXqvk4b1DPlqsSmC4dj8ViSu/izp/VJPEcrp8ntqn+cVN1WwtZh5jg54yM+jLNCjY/+wi4rwc++wQNmcCKmAEzDY=
  on:
    repo: boennemann/zentodone
    tags: true
addons:
  sauce_connect:
    username: zentodone
    access_key:
      secure: Nt1qAd1PZmTI2oQ6YbYvXkDiJFQeo73x0hwNiKHTfxhC6EmWSO23CAA/dU2NtkW+kKRurNbq9hayO9rJf+K7y85dfhFrEjmp0acKdQkAZR5G0dm8aF5xJnRkFgDIBEmgXr5+O1bcDka4/7j+dlZv+clBNOSAH4BLlUzdsK6M6gk=
